/**
 * Role-family taxonomy for Clear Routes.
 *
 * Data-only increment (see prompt in chat history). Classifies every DB role
 * into a maintainable family + archetype + Reality Check depth signal so we
 * do not need 1,245 bespoke Reality Check questionnaires.
 *
 * - Data lives in `role-taxonomy.json` (auto-generated by scripts/classify).
 * - This file provides the types, a strongly-typed loader, and helpers
 *   (summary counts, top-candidate shortlist).
 * - No UI, no engines, no LLM. Existing Electrician/Plumber/HVAC modular
 *   Reality Checks are unaffected — they are asserted frozen in the tests.
 */

import raw from "./role-taxonomy.json";

export const ROUTE_FAMILIES = [
  "skilled_trades",
  "construction_built_environment",
  "digital_product_technology",
  "data_ai_analytics",
  "healthcare_clinical",
  "care_social_support",
  "education_training",
  "public_service_security",
  "legal_finance_professional",
  "creative_media_content",
  "engineering_manufacturing",
  "science_research_environment",
  "transport_aviation_logistics",
  "business_operations_commercial",
  "hospitality_retail_service",
  "beauty_wellness_personal_services",
  "agriculture_land_animal",
  "elite_competitive_long_route",
] as const;
export type RouteFamily = (typeof ROUTE_FAMILIES)[number];

export const ROUTE_ARCHETYPES = [
  "apprenticeship_led",
  "degree_led",
  "regulated_registration_led",
  "licence_led",
  "portfolio_led",
  "experience_led",
  "employer_training_led",
  "self_employment_led",
  "commission_or_gig_led",
  "selection_led",
  "competitive_entry_led",
  "feeder_pathway_led",
  "postgraduate_led",
  "short_course_risk",
  "mixed_route",
] as const;
export type RouteArchetype = (typeof ROUTE_ARCHETYPES)[number];

export type RealityCheckDepth =
  | "standard_role_page"
  | "light_route_checker"
  | "deep_reviewed_reality_check";

export type DeepCheckPriority =
  | "not_priority"
  | "possible_later"
  | "strong_candidate"
  | "top_candidate";

export type DeepCheckRubric = {
  regulated: boolean;
  expensiveWrongTurn: boolean;
  routeConfusion: 0 | 1 | 2;
  demandLikely: 0 | 1 | 2;
  highConsequenceAdvice: boolean;
};

export type RoleTaxonomyEntry = {
  roleSlug: string;
  roleName: string;
  primaryFamily: RouteFamily;
  secondaryFamily?: RouteFamily;
  routeArchetype: RouteArchetype;
  secondaryArchetype?: RouteArchetype;
  recommendedRealityCheckDepth: RealityCheckDepth;
  deepCheckRubric: DeepCheckRubric;
  deepCheckPriority: DeepCheckPriority;
  confidence: "high" | "needs_review";
  notes?: string;
};

export const ROLE_TAXONOMY: readonly RoleTaxonomyEntry[] =
  raw as readonly RoleTaxonomyEntry[];

/** Score derived from the rubric. Priority buckets: 8+ top, 5–7 strong, 2–4 possible, 0–1 not. */
export function rubricScore(r: DeepCheckRubric): number {
  return (
    (r.regulated ? 2 : 0) +
    (r.expensiveWrongTurn ? 2 : 0) +
    r.routeConfusion +
    r.demandLikely +
    (r.highConsequenceAdvice ? 2 : 0)
  );
}

export function priorityFromScore(score: number): DeepCheckPriority {
  if (score >= 8) return "top_candidate";
  if (score >= 5) return "strong_candidate";
  if (score >= 2) return "possible_later";
  return "not_priority";
}

/** Slugs of the three frozen reviewed roles. */
export const FROZEN_DEEP_ROLES: readonly string[] = [
  "electrician",
  "plumber",
  "hvac-engineer",
] as const;

export function getTaxonomyEntry(slug: string): RoleTaxonomyEntry | undefined {
  return ROLE_TAXONOMY.find((e) => e.roleSlug === slug);
}

export type TaxonomySummary = {
  totalRoles: number;
  byFamily: Record<RouteFamily, number>;
  byArchetype: Record<RouteArchetype, number>;
  byDepth: Record<RealityCheckDepth, number>;
  byPriority: Record<DeepCheckPriority, number>;
  byConfidence: Record<"high" | "needs_review", number>;
  shortlist: RoleTaxonomyEntry[]; // 15–25 top deep-check candidates
  needsReview: RoleTaxonomyEntry[];
};

export function summarise(
  entries: readonly RoleTaxonomyEntry[] = ROLE_TAXONOMY,
): TaxonomySummary {
  const zero = <K extends string>(keys: readonly K[]) =>
    Object.fromEntries(keys.map((k) => [k, 0])) as Record<K, number>;

  const byFamily = zero(ROUTE_FAMILIES);
  const byArchetype = zero(ROUTE_ARCHETYPES);
  const byDepth: Record<RealityCheckDepth, number> = {
    standard_role_page: 0,
    light_route_checker: 0,
    deep_reviewed_reality_check: 0,
  };
  const byPriority: Record<DeepCheckPriority, number> = {
    not_priority: 0,
    possible_later: 0,
    strong_candidate: 0,
    top_candidate: 0,
  };
  const byConfidence: Record<"high" | "needs_review", number> = {
    high: 0,
    needs_review: 0,
  };

  for (const e of entries) {
    byFamily[e.primaryFamily]++;
    byArchetype[e.routeArchetype]++;
    byDepth[e.recommendedRealityCheckDepth]++;
    byPriority[e.deepCheckPriority]++;
    byConfidence[e.confidence]++;
  }

  const frozen = new Set(FROZEN_DEEP_ROLES);
  const topCandidates = entries
    .filter((e) => e.deepCheckPriority === "top_candidate" && !frozen.has(e.roleSlug))
    .sort((a, b) => {
      const sa = rubricScore(a.deepCheckRubric);
      const sb = rubricScore(b.deepCheckRubric);
      if (sb !== sa) return sb - sa;
      const da = a.deepCheckRubric.demandLikely - b.deepCheckRubric.demandLikely;
      if (da !== 0) return -da;
      return b.deepCheckRubric.routeConfusion - a.deepCheckRubric.routeConfusion;
    });

  const shortlist = topCandidates.slice(0, 25);
  const needsReview = entries.filter((e) => e.confidence === "needs_review");

  return {
    totalRoles: entries.length,
    byFamily,
    byArchetype,
    byDepth,
    byPriority,
    byConfidence,
    shortlist,
    needsReview,
  };
}
