/**
 * Role-family taxonomy for Clear Routes.
 *
 * Data-only increment. Classifies every DB role into a maintainable family +
 * archetype + Reality Check depth signal so we do not need 1,245 bespoke
 * Reality Check questionnaires.
 *
 * - Data lives in `role-taxonomy.json` (generated by scripts/build-role-taxonomy.py
 *   and enriched by scripts/enrich-role-taxonomy.py).
 * - No UI, no engines, no LLM. Existing Electrician/Plumber/HVAC modular
 *   Reality Checks are unaffected — they are asserted frozen in the tests.
 * - The rubric now includes `productProofValue` so the shortlist answers
 *   "which role should Clear Routes build next to prove a new type of route
 *   logic" and not merely "which role is most formally regulated".
 */

import raw from "./role-taxonomy.json";

export const ROUTE_FAMILIES = [
  "skilled_trades",
  "construction_built_environment",
  "digital_data_technology",
  "healthcare_clinical",
  "care_social_support",
  "education_training",
  "public_service_security",
  "legal_finance_professional",
  "creative_media_content",
  "engineering_manufacturing",
  "science_research_environment",
  "transport_aviation_logistics",
  "business_operations_commercial",
  "hospitality_retail_personal_service",
  "agriculture_land_animal",
  "elite_competitive_long_route",
] as const;
export type RouteFamily = (typeof ROUTE_FAMILIES)[number];

export const ROUTE_ARCHETYPES = [
  "apprenticeship_led",
  "degree_led",
  "regulated_registration_led",
  "licence_led",
  "portfolio_led",
  "experience_led",
  "employer_training_led",
  "self_employment_led",
  "commission_or_gig_led",
  "selection_led",
  "competitive_entry_led",
  "feeder_pathway_led",
  "postgraduate_led",
  "short_course_risk",
  "mixed_route",
] as const;
export type RouteArchetype = (typeof ROUTE_ARCHETYPES)[number];

export type RealityCheckDepth =
  | "standard_role_page"
  | "light_route_checker"
  | "deep_reviewed_reality_check";

export type DeepCheckPriority =
  | "not_priority"
  | "possible_later"
  | "strong_candidate"
  | "top_candidate";

export type DeepCheckRubric = {
  regulated: boolean;
  expensiveWrongTurn: boolean;
  routeConfusion: 0 | 1 | 2;
  demandLikely: 0 | 1 | 2;
  highConsequenceAdvice: boolean;
  /**
   * How useful this role is for proving Clear Routes can handle a distinct
   * route-logic family beyond the current skilled-trades module.
   * 0 = similar to an existing module / not strategically useful yet
   * 1 = some distinct logic, not a strong proof case
   * 2 = strong proof of a new route family or high-value decision pattern
   */
  productProofValue: 0 | 1 | 2;
};

export type RoleTaxonomyEntry = {
  roleSlug: string;
  roleName: string;
  primaryFamily: RouteFamily;
  secondaryFamily?: RouteFamily;
  routeArchetype: RouteArchetype;
  secondaryArchetype?: RouteArchetype;
  recommendedRealityCheckDepth: RealityCheckDepth;
  deepCheckRubric: DeepCheckRubric;
  deepCheckPriority: DeepCheckPriority;
  confidence: "high" | "needs_review";
  notes?: string;
};

export const ROLE_TAXONOMY: readonly RoleTaxonomyEntry[] =
  raw as readonly RoleTaxonomyEntry[];

/**
 * Score derived from the rubric. Max = 14.
 * Buckets:
 *   top_candidate   >= 10
 *   strong_candidate  6..9
 *   possible_later    2..5
 *   not_priority      0..1
 *
 * productProofValue is weighted 2x so a role can climb into the shortlist
 * because it proves a valuable new route type, not only because it is
 * heavily regulated.
 */
export function rubricScore(r: DeepCheckRubric): number {
  return (
    (r.regulated ? 2 : 0) +
    (r.expensiveWrongTurn ? 2 : 0) +
    r.routeConfusion +
    r.demandLikely +
    (r.highConsequenceAdvice ? 2 : 0) +
    2 * r.productProofValue
  );
}

export function priorityFromScore(score: number): DeepCheckPriority {
  if (score >= 10) return "top_candidate";
  if (score >= 6) return "strong_candidate";
  if (score >= 2) return "possible_later";
  return "not_priority";
}

/** Slugs of the frozen reviewed roles (deep_reviewed_reality_check depth). */
export const FROZEN_DEEP_ROLES: readonly string[] = [
  "electrician",
  "plumber",
  "hvac-engineer",
  "software-engineer",
  "registered-nurse",
  "police-officer",
  "actor",
] as const;

export function getTaxonomyEntry(slug: string): RoleTaxonomyEntry | undefined {
  return ROLE_TAXONOMY.find((e) => e.roleSlug === slug);
}

export type ShortlistEntry = RoleTaxonomyEntry & {
  score: number;
  whyCandidate: string;
  differentFromTradesModule: string;
};

export type TaxonomySummary = {
  totalRoles: number;
  byFamily: Record<RouteFamily, number>;
  byArchetype: Record<RouteArchetype, number>;
  byDepth: Record<RealityCheckDepth, number>;
  byPriority: Record<DeepCheckPriority, number>;
  byConfidence: Record<"high" | "needs_review", number>;
  byProductProof: Record<0 | 1 | 2, number>;
  /** Pure score-based top 25 (excludes frozen). */
  overallTop25: ShortlistEntry[];
  /** Top 25 with at most 3 roles per primaryFamily. */
  balancedTop25: ShortlistEntry[];
  /** 10–15 roles chosen to prove distinct route-logic families. */
  strategicProofShortlist: ShortlistEntry[];
  /** Kept for backwards-compat: same list as overallTop25. */
  shortlist: ShortlistEntry[];
  needsReview: RoleTaxonomyEntry[];
};

/** Human-readable rubric justification derived entirely from the flags. */
export function explainRubric(e: RoleTaxonomyEntry): string {
  const r = e.deepCheckRubric;
  const parts: string[] = [];
  if (r.regulated) parts.push("regulated (protected title/register)");
  if (r.expensiveWrongTurn) parts.push("expensive wrong turn");
  if (r.routeConfusion === 2) parts.push("high route confusion");
  else if (r.routeConfusion === 1) parts.push("some route confusion");
  if (r.demandLikely === 2) parts.push("high demand");
  else if (r.demandLikely === 1) parts.push("moderate demand");
  if (r.highConsequenceAdvice) parts.push("high-consequence advice");
  if (r.productProofValue === 2) parts.push("strong new-route-logic proof");
  else if (r.productProofValue === 1) parts.push("some new-route-logic proof");
  return parts.length
    ? `Score ${rubricScore(r)}/14: ${parts.join(", ")}.`
    : `Score ${rubricScore(r)}/14.`;
}

/** How this role's Reality Check would differ from the skilled-trades module. */
export function differsFromTradesModule(e: RoleTaxonomyEntry): string {
  switch (e.routeArchetype) {
    case "regulated_registration_led":
      return "Statutory register + protected title; the checker centres on registration eligibility, prior-learning recognition and body-specific route (not Gas Safe/electrical certs).";
    case "licence_led":
      return "Licence/certification chain (not trade card); focus on licence prerequisites, medicals, background checks and renewal cadence.";
    case "portfolio_led":
      return "Portfolio + credit-based hiring, not time-served apprenticeship; checker weighs body-of-work, briefs and freelance viability.";
    case "commission_or_gig_led":
      return "Paid-work-as-route; income variability, agent/rep dynamics and credit-building replace an employer training plan.";
    case "selection_led":
      return "Assessment-heavy entry (fitness, vetting, aptitude); checker probes selection standards, prior offences and residency, not trade eligibility.";
    case "competitive_entry_led":
      return "Small-number, high-competition entry; realistic-odds framing and feeder-pathway options matter more than route mechanics.";
    case "postgraduate_led":
      return "Long stacked-degree route with funding cliffs; checker maps UG → Masters/DClin/PhD costs and clinical placement supply.";
    case "degree_led":
      return "Degree-plus-conversion routes with employer variance; checker weighs course selectivity, placement year value and grad-scheme odds vs self-taught paths.";
    case "short_course_risk":
      return "Warn about weak private courses / mis-selling; checker names credible awarding bodies and highlights regulator status.";
    case "self_employment_led":
      return "Client acquisition + business viability, not employment; checker probes insurance, tax status, pricing floor and demand geography.";
    case "employer_training_led":
      return "Entry-level with on-the-job training; checker focuses on progression ceilings and pay realism, not qualifications.";
    case "experience_led":
      return "Reached via years in adjacent roles; checker maps typical stepping-stone titles and how long each takes.";
    case "feeder_pathway_led":
      return "Depends on prior career (military/athletic/teaching); checker asks about the feeder role and transition timing.";
    case "apprenticeship_led":
      return "Apprenticeship pattern like trades, but different awarding body/register — checker adapts the skilled-trades module rather than reinventing it.";
    default:
      return "Multiple viable routes; checker's main job is helping the user choose between them.";
  }
}

/** Deterministic comparator per prompt spec. */
function shortlistCompare(a: RoleTaxonomyEntry, b: RoleTaxonomyEntry): number {
  const sa = rubricScore(a.deepCheckRubric);
  const sb = rubricScore(b.deepCheckRubric);
  if (sb !== sa) return sb - sa;
  const pp = b.deepCheckRubric.productProofValue - a.deepCheckRubric.productProofValue;
  if (pp !== 0) return pp;
  const rc = b.deepCheckRubric.routeConfusion - a.deepCheckRubric.routeConfusion;
  if (rc !== 0) return rc;
  const ew =
    Number(b.deepCheckRubric.expensiveWrongTurn) -
    Number(a.deepCheckRubric.expensiveWrongTurn);
  if (ew !== 0) return ew;
  const hc =
    Number(b.deepCheckRubric.highConsequenceAdvice) -
    Number(a.deepCheckRubric.highConsequenceAdvice);
  if (hc !== 0) return hc;
  const dl = b.deepCheckRubric.demandLikely - a.deepCheckRubric.demandLikely;
  if (dl !== 0) return dl;
  return a.roleName.localeCompare(b.roleName);
}

function decorate(e: RoleTaxonomyEntry): ShortlistEntry {
  return {
    ...e,
    score: rubricScore(e.deepCheckRubric),
    whyCandidate: explainRubric(e),
    differentFromTradesModule: differsFromTradesModule(e),
  };
}

export function summarise(
  entries: readonly RoleTaxonomyEntry[] = ROLE_TAXONOMY,
): TaxonomySummary {
  const zero = <K extends string>(keys: readonly K[]) =>
    Object.fromEntries(keys.map((k) => [k, 0])) as Record<K, number>;

  const byFamily = zero(ROUTE_FAMILIES);
  const byArchetype = zero(ROUTE_ARCHETYPES);
  const byDepth: Record<RealityCheckDepth, number> = {
    standard_role_page: 0,
    light_route_checker: 0,
    deep_reviewed_reality_check: 0,
  };
  const byPriority: Record<DeepCheckPriority, number> = {
    not_priority: 0,
    possible_later: 0,
    strong_candidate: 0,
    top_candidate: 0,
  };
  const byConfidence: Record<"high" | "needs_review", number> = {
    high: 0,
    needs_review: 0,
  };
  const byProductProof: Record<0 | 1 | 2, number> = { 0: 0, 1: 0, 2: 0 };

  for (const e of entries) {
    byFamily[e.primaryFamily]++;
    byArchetype[e.routeArchetype]++;
    byDepth[e.recommendedRealityCheckDepth]++;
    byPriority[e.deepCheckPriority]++;
    byConfidence[e.confidence]++;
    byProductProof[e.deepCheckRubric.productProofValue]++;
  }

  const frozen = new Set<string>(FROZEN_DEEP_ROLES);
  const eligible = entries.filter((e) => !frozen.has(e.roleSlug));
  const ranked = [...eligible].sort(shortlistCompare);

  // A. Overall top 25 — pure score, top_candidate priority only.
  const overallTop25 = ranked
    .filter((e) => e.deepCheckPriority === "top_candidate")
    .slice(0, 25)
    .map(decorate);

  // B. Balanced top 25 — cap of 3 per primaryFamily, top_candidate priority.
  const familyCap: Partial<Record<RouteFamily, number>> = {};
  const balancedTop25: ShortlistEntry[] = [];
  for (const e of ranked) {
    if (e.deepCheckPriority !== "top_candidate") continue;
    const c = familyCap[e.primaryFamily] ?? 0;
    if (c >= 3) continue;
    familyCap[e.primaryFamily] = c + 1;
    balancedTop25.push(decorate(e));
    if (balancedTop25.length >= 25) break;
  }

  // C. Strategic proof shortlist — 10–15 roles proving distinct route logic.
  //    Priority: productProofValue == 2, then one entry per (family, archetype)
  //    pair so each pick unlocks a different Reality Check module. Within each
  //    bucket we prefer curated exemplar names (Software Engineer, Registered
  //    Nurse, Police Officer, Actor, Commercial Pilot, Solicitor, Data Analyst,
  //    Cybersecurity Analyst, etc.) so the shortlist reads as product proof
  //    cases rather than the alphabetically-earliest role in a bucket.
  const EXEMPLAR_NAMES = new Set(
    [
      "Software Engineer","Software Developer","Web Developer","Full Stack Developer",
      "Data Analyst","Data Scientist","Cybersecurity Analyst","AI Product Manager",
      "Registered Nurse","Midwife","Paramedic","Clinical Psychologist",
      "Physiotherapist","Pharmacist","Dentist","Veterinary Surgeon",
      "Police Officer","Firefighter","Prison Officer","Border Force Officer",
      "Actor","Musician","Photographer","Journalist","Fashion Designer",
      "Film Director","Screenwriter","Graphic Designer",
      "Commercial Pilot","Airline Pilot","Air Traffic Controller",
      "Solicitor","Barrister","Chartered Accountant","Architect",
      "Primary School Teacher","Secondary School Teacher",
      "Social Worker","Adult Social Worker","Children's Social Worker",
      "Chef","Personal Trainer","Counsellor / Psychotherapist",
      "Astronaut","Professional Footballer",
    ],
  );
  const proofCompare = (a: RoleTaxonomyEntry, b: RoleTaxonomyEntry) => {
    const pp = b.deepCheckRubric.productProofValue - a.deepCheckRubric.productProofValue;
    if (pp !== 0) return pp;
    const ex = Number(EXEMPLAR_NAMES.has(b.roleName)) - Number(EXEMPLAR_NAMES.has(a.roleName));
    if (ex !== 0) return ex;
    return shortlistCompare(a, b);
  };
  const seenPair = new Set<string>();
  const strategicProofShortlist: ShortlistEntry[] = [];
  const proofRanked = [...eligible].sort(proofCompare);
  for (const e of proofRanked) {
    if (e.deepCheckRubric.productProofValue < 1) break;
    if (strategicProofShortlist.length >= 15) break;
    const key = `${e.primaryFamily}::${e.routeArchetype}`;
    if (seenPair.has(key)) continue;
    if (
      strategicProofShortlist.length < 10 &&
      e.deepCheckRubric.productProofValue < 2
    ) {
      continue;
    }
    seenPair.add(key);
    strategicProofShortlist.push(decorate(e));
  }
  if (strategicProofShortlist.length < 10) {
    for (const e of proofRanked) {
      if (strategicProofShortlist.length >= 15) break;
      if (e.deepCheckRubric.productProofValue < 1) break;
      const key = `${e.primaryFamily}::${e.routeArchetype}`;
      if (seenPair.has(key)) continue;
      seenPair.add(key);
      strategicProofShortlist.push(decorate(e));
    }
  }

  const needsReview = entries.filter((e) => e.confidence === "needs_review");

  return {
    totalRoles: entries.length,
    byFamily,
    byArchetype,
    byDepth,
    byPriority,
    byConfidence,
    byProductProof,
    overallTop25,
    balancedTop25,
    strategicProofShortlist,
    shortlist: overallTop25,
    needsReview,
  };
}
